# Generated by Django 5.2.7 on 2025-10-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('seat_type', models.CharField(blank=True, choices=[('business', 'Business'), ('economy', 'Economy')], max_length=10, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=5, null=True)),
                ('affiliated_passenger_ids', models.JSONField(blank=True, null=True)),
                ('parent_passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='PassengerApi.passenger')),
            ],
        ),
    ]
