# Generated by Django 5.2.7 on 2025-11-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(help_text='Airport code (AAA format).', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_flight_number', models.CharField(help_text="Partner airline's flight number (AANNNN format).", max_length=6)),
                ('partner_company_name', models.CharField(max_length=100)),
                ('connecting_flight_info', models.TextField(blank=True, help_text='Details on any additional connecting flight (optional).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('total_seats', models.IntegerField(help_text='Total number of passenger seats.')),
                ('max_flight_crew', models.IntegerField(help_text='Maximum allowed flight crew (pilots).')),
                ('max_cabin_crew', models.IntegerField(help_text='Maximum allowed cabin crew.')),
                ('seating_plan_info', models.TextField(help_text='JSON or descriptive text detailing seat layout.')),
                ('standard_menu', models.TextField(help_text='Description of the standard menu served.')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(help_text='Unique flight ID (AANNNN format).', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('departure_time', models.DateTimeField(help_text='The date and time the flight is scheduled to take off.')),
                ('duration_minutes', models.IntegerField(help_text='Duration of the flight in minutes.')),
                ('distance_km', models.IntegerField(help_text='Flight distance in kilometers.')),
                ('destination', models.ForeignKey(help_text='Destination airport.', on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='FlightInfoApi.airport')),
                ('source', models.ForeignKey(help_text='Originating airport.', on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='FlightInfoApi.airport')),
                ('shared_info', models.OneToOneField(blank=True, help_text='Optional link to shared flight details.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FlightInfoApi.sharedflightinfo')),
                ('vehicle_type', models.ForeignKey(help_text='The type of aircraft used for this flight.', on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='FlightInfoApi.vehicletype')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
    ]
