# Generated by Django 5.2.6 on 2025-11-26 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Code must be 3 uppercase letters')])),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seat_capacity', models.IntegerField()),
                ('crew_limit', models.IntegerField()),
                ('seating_plan_layout', models.JSONField(help_text='JSON structure of seat coordinates')),
                ('standard_menu', models.TextField(help_text='Standard menu served on this vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{4}$', 'Format must be AANNNN')])),
                ('departure_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('distance', models.FloatField()),
                ('is_shared', models.BooleanField(default=False)),
                ('partner_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_flight_number', models.CharField(blank=True, max_length=6, null=True)),
                ('connecting_flight_info', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='FlightInfoApi.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='FlightInfoApi.airport')),
                ('plane_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FlightInfoApi.planetype')),
            ],
        ),
    ]
