# Generated by Django 5.2.6 on 2025-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=10, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('roster_data', models.JSONField()),
            ],
        ),
    ]
