# Generated by Django 5.2.6 on 2025-11-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FlightInfoApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('known_languages', models.CharField(max_length=200)),
                ('attendant_type', models.CharField(choices=[('CHIEF', 'Chief'), ('REGULAR', 'Regular'), ('CHEF', 'Chef')], max_length=10)),
                ('allowed_vehicles', models.ManyToManyField(to='FlightInfoApi.planetype')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='CabinCrewApi.attendant')),
            ],
        ),
    ]
