# Generated by Django 5.2.6 on 2025-11-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FlightInfoApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('known_languages', models.CharField(max_length=200)),
                ('allowed_range', models.FloatField()),
                ('seniority', models.CharField(choices=[('TRAINEE', 'Trainee'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], max_length=10)),
                ('allowed_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FlightInfoApi.planetype')),
            ],
        ),
    ]
